spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
       # url: jdbc:mysql://localhost:3306/foojhipster?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password:
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    jpa:
#        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#        database: MYSQL
        show-sql: false
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: io.github.jhipster.config.jcache.NoDefaultJCacheRegionFactor
            hibernate.ddl-auto: none

liquibase:
    contexts: prod

endpoints
    enabled: false
    info:
        enabled: true
    health:
        enabled: true
    metrics:
        enabled: true
    env:
        enabled: true
    loggers:
        enabled: true
    dump: #Thread
        enabled: true
    trace: #http
        enabled: true
    auditevents: #audit
        enabled: true
    logfile:
        enabled: true