spring:
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true

#    jackson:
#        serialization.indent_output: true

    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:file:./target/h2db/db/nice;DB_CLOSE_DELAY=-1
        username: foo
        password:

    jpa:
#        database-platform: io.github.jhipster.domain.util.FixedH2Dialect
#        database: H2
        show-sql: true
        properties:
#            hibernate.id.new_generator_mappings: true
#            hibernate.cache.use_second_level_cache: true
#            hibernate.cache.use_query_cache: false
#            hibernate.generate_statistics: true
#            hibernate.cache.region.factory_class: io.github.jhipster.config.jcache.NoDefaultJCacheRegionFactory
            hibernate.ddl-auto: create-drop #none

liquibase:
    contexts: dev